### ISSUE TITLE
`read_deltalake` breaks with dask>=2024.3.1

### ISSUE THREAD

**Issue by avriiil** [dask-contrib/dask-deltatable#79]
Hey folks! Amazing work on the query planning functionality with `dask-expr` :) 
I was just running some `deltalake` queries and it seems like this upgrade is interfering with `read_deltalake`

I'm getting a `NotImplementedError: dask_expr does not support a token argument.` when running the code snippet below:

### **To reproduce**:

```
from deltalake import write_deltalake
import dask_deltatable as ddt
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame({
    "group": [1, 1, 2, 2, 3, 3, 4, 4],
    "num": list(range(8)),
    "letter": ["a", "b", "c", "d", "e", "f", "g", "h"],
})

write_deltalake("some-table", df, partition_by="group")

delta_path = "some-table"
ddf = ddt.read_deltalake(delta_path)
```

### **To fix**:
- downgrade `Dask==2024.2.1`
- OR run
```
import dask
dask.config.set({'dataframe.query-planning': False})
```

EDIT
I've tried upgrading `dask-expr` as suggested [here](https://github.com/dask/dask/issues/10995). This upgrades Dask to 2024.4.1 but does not fix the issue for me.

**Comment by milesgranger** [comment]
Hi @avriiil, this should have been fixed in https://github.com/dask-contrib/dask-deltatable/commit/ec1c90c982061446944a2080f459cc1c04a8bc8a, but hasn't been released. Are you / could you try installing from source and see if that fixes things for you?

**Comment by avriiil** [comment]
Thanks @milesgranger! I don't have time to test that right now, workaround is fine for me atm just wanted to flag it for the dev team. Happy to wait for the release, thanks so much for your help :)

**Comment by jacobtomlinson** [comment]
Good to see you around @avriiil! I'm going to close this as resolved in #78.

**Comment by avriiil** [comment]
@jacobtomlinson @milesgranger  I'm still getting the same `NotImplementedError` on `dask==2024.5.1` with `deltalake==0.13.0`

**Comment by jacobtomlinson** [comment]
cc @phofl @rjzamora in case you have thoughts here?

**Comment by avriiil** [comment]
@rjzamora -- I can confirm that downgrading `python==3.11.8` works.

**Comment by phofl** [comment]
We've merged a PR now that should make stuff run smoothly with dask-expr.
